title: TrueKYC Documentation - User Guide
description: Need help using TrueKYC? Find out how to get started with customers, KYC verification, levels, transactions and more.
theme: just-the-docs
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
url: https://truekyc-docs.github.io

aux_links:
  TrueKYC: https://truekyc.io
  Truezone: https://truezone.io