title: TrueKYC Documentation - User Guide
description: Need help using TrueKYC? Find out how to get started with customers, KYC verification, levels, transactions and more.
theme: just-the-docs
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
url: "docs.truekyc.io"
baseurl: ""
repository: truezoneio/truekyc-docs

permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  TrueKYC: https://truekyc.io
  Truezone: https://truezone.io

callouts:
  note:
    title: Note
    color: yellow
  important:
    title: Important
    color: blue
  warning:
    title: Warning
    color: red